document = type;

type = object | array | basicType;
basicType = nullSymbol | booleanSymbol | stringSymbol | numberSymbol; 

object = "{" [{property ","} property] "}"; 
property = stringSymbol ":" type; 

array = "[" [{type ","} type] "]";

nullSymbol = "null";
booleanSymbol = "true" | "false";

stringSymbol = "a string as defined by json dot org including surrounding \" "; 
numberSymbol = "a number as defined by json dot org";


Below is the ebnf definition for jsonc. Not included are comments and white spaces. Besically around all the tokens can be white spaces or comments in the form of /* comment */. At the end of every line can be a comment in the form of \\ comment.

document = type;

type = object | array | basicType;
basicType = nullSymbol | booleanSymbol | string | number; 

object = "{" [{property [","] } property] "}"; 
property = string ":" type; 

array = "[" [{type [","]} type] "]";

nullSymbol = "null";
booleanSymbol = "true" | "false";

string = stringToken | stringMultiline | jsonString; 

stringToken = "a string containing only digits or letters.";
stringMultiline = "`" {stringSymbol lineBreak {lineBreak}} stringSymbol {lineBreak} "`";
jsonString = "a string as defined by json dot org including surrounding \" "; 
lineBreak = "the line break character \n";

number = "a number as defined by json dot org";
